name: iConomy
main: com.iConomy.iConomy
version: ${project.version}
authors: [Nijikokun]
commands:
    money:
        description: Controls account balances and more
        usage:
    bank:
        description: Control, list, create, and do various bank features.
        usage: